<a href="https://colab.research.google.com/github/sydney-machine-learning/COVID19-antivaccine_sentiment/blob/main/Geo_tagged_dataset_LSTM_IEEE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch==1.7.0 
!pip install torchtext==0.8.0

     |████████████████████████████████| 776.8MB 24kB/s 
ERROR: torchvision 0.9.1+cu101 has requirement torch==1.8.1, but you'll have torch 1.7.0 which is incompatible.
ERROR: torchtext 0.9.1 has requirement torch==1.8.1, but you'll have torch 1.7.0 which is incompatible.
  Found existing installation: torch 1.8.1+cu101
    Uninstalling torch-1.8.1+cu101:
      Successfully uninstalled torch-1.8.1+cu101
     |████████████████████████████████| 7.0MB 5.3MB/s 
  Found existing installation: torchtext 0.9.1
    Uninstalling torchtext-0.9.1:
      Successfully uninstalled torchtext-0.9.1


In [2]:
#!pip install torchtext

In [3]:
import pickle
import torch
import torch.nn as nn
import torch.nn.functional as F
SEED = 1024
torch.manual_seed(SEED)
torch.cuda.manual_seed(SEED)
torch.backends.cudnn.deterministic = True

from torch.utils.data import TensorDataset, DataLoader, Dataset
import torchtext
from torchtext import data

import warnings
warnings.filterwarnings('ignore')
import operator

from sklearn.metrics import hamming_loss, jaccard_score, label_ranking_average_precision_score, f1_score
from tqdm._tqdm_notebook import tqdm_notebook as tqdm

In [4]:
import spacy
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from wordcloud import WordCloud
import re
import unicodedata
import nltk
import csv
import string
from textblob import TextBlob
from nltk.corpus import stopwords
!pip install demoji
nltk.download('all')
import demoji

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_esp.zip.
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Unzipp

In [5]:
print(torch.__version__)

1.7.0


In [6]:
demoji.download_codes()

... OK (Got response in 0.11 seconds)
Writing emoji data to /root/.demoji/codes.json ...
... OK


In [15]:
from google.colab import drive
drive.mount("/content/gdrive")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [17]:
import pandas as pd
tweet_df = pd.read_csv('/content/gdrive/My Drive/geo tagged data/geo tagged final.csv')#lineterminator='\r'
#tweet_df = tweet_df.replace('\n','', regex=True)
#tweet_df = tweet_df.dropna()
print(tweet_df.head(5))

                coordinates  ...                          geometry
0   77.39760968,28.51873311  ...   POINT (77.39760968 28.51873311)
1  -80.13934722,26.12700768  ...  POINT (-80.13934722 26.12700768)
2        -79.16659,43.77102  ...        POINT (-79.16659 43.77102)
3  -73.87320303,50.42075843  ...  POINT (-73.87320303 50.42075843)
4      110.366643,-7.799243  ...      POINT (110.366643 -7.799243)

[5 rows x 6 columns]


In [19]:
def emoji2text(tweet):
        emojis = demoji.findall(tweet)
        new_tweet = []
        for word in tweet.split():
            if word in emojis.keys():
                tweet = tweet.replace(word, emojis[word])
                new_tweet.append(emojis[word])
            wordmojis = demoji.findall(word)
            for char in word:
                if char in wordmojis.keys():
                    tweet = tweet.replace(word, wordmojis[char])
        return tweet
        

tweet_df['text'] = tweet_df['text'].apply(lambda x : emoji2text(x))

In [20]:
class CustomLSTM(nn.Module):
    def __init__(self, embedding_dim, vocab, hidden_dim, output_dim, drop_prob, bidirectional = False, use_glove = True):
        super().__init__()
        self.embeddings = nn.Embedding(len(vocab), embedding_dim)
        if use_glove:
            self.embeddings.weight.data.copy_(vocab.vectors)
            self.embeddings.weight.requires_grad = False
        self.drop_prob = drop_prob

        self.lstm = nn.LSTM(embedding_dim, hidden_dim, bidirectional = bidirectional, batch_first = True, num_layers = 2)
        if bidirectional is True:
            self.lin = nn.Linear(2*hidden_dim, 64)
        else:
            self.lin = nn.Linear(hidden_dim, 64)
        self.fc = nn.Linear(64, output_dim)
        self.dropout = nn.Dropout(p = drop_prob)
    def forward(self, sentence):
        #sentence = [max_len, batch_size]

        embed = self.embeddings(torch.transpose(sentence, 0, 1))
        #embed = [batch_size, max_len, embedding_dim]
        
        if self.drop_prob:
            embed = self.dropout(embed)
        
        lstm_out, (hidden, cell) = self.lstm(embed)
        #lstm_out = [batch_size, max_len, 2*hidden_dim if bidirectional else hidden_dim]
        #hidden = [num_layers, batch_size, hidden_dim]
        #cell = [num_layers, batch_size, hidden_dim]
        
        out = lstm_out[:,-1,:].squeeze()
        #out = [batch_size, 2*hidden_dim if bidirectional else hidden_dim]
        
        out = self.lin(out)
        #out = [batch_size, 64]

        outputs = self.fc(out)
        #outputs = [batch_size, output_dim]
        
        return outputs

In [21]:
def evaluation_metrics(actual_labels, pred_labels, threshold):
    int_pred_labels = pred_labels
    for i in range(len(pred_labels)):
        for j in range(11):
            if int_pred_labels[i][j] >= threshold: int_pred_labels[i][j] = 1
            else:
                int_pred_labels[i][j] = 0
    
    ham_loss = hamming_loss(actual_labels, int_pred_labels)
    jacc_score = jaccard_score(actual_labels, int_pred_labels, average = 'samples')
    lrap = label_ranking_average_precision_score(actual_labels, pred_labels)
    f1_macro = f1_score(actual_labels, int_pred_labels, average = 'macro')
    f1_micro = f1_score(actual_labels, int_pred_labels, average = 'micro')

    return ham_loss, jacc_score, lrap, f1_macro, f1_micro

In [22]:
model = torch.load('/content/gdrive/My Drive/model7LSTM.pth',map_location ='cpu')
model

CustomLSTM(
  (embeddings): Embedding(13666, 300)
  (lstm): LSTM(300, 128, num_layers=2, batch_first=True)
  (lin): Linear(in_features=128, out_features=64, bias=True)
  (fc): Linear(in_features=64, out_features=11, bias=True)
  (dropout): Dropout(p=0.65, inplace=False)
)

In [24]:
import spacy
spacy_en = spacy.load('en')

def tokenizer(tweet):
    tweet = re.sub(r'[\n]', ' ', tweet)
    return [tok.text for tok in spacy_en.tokenizer(tweet)]

tweet_field = data.Field(sequential = True, lower = True, tokenize = tokenizer)
dataFields = [("coordinates", None), ("text", tweet_field), ("sentiment_score", None),("longitude", None),("latitude", None),("geometry", None)]

train_dataset = data.TabularDataset(
    path = '/content/gdrive/My Drive/geo tagged data/geo tagged final.csv', format = 'csv', fields = dataFields, skip_header = True
    )

In [25]:
print(train_dataset) 

In [26]:
print("length of dataset:", len(train_dataset))

length of dataset: 3825


In [27]:
def check_coverage(vocab, embeddings_index):
    a = {}
    oov = {}
    k = 0
    i = 0
    for word in tqdm(vocab):
        try:
            a[word] = embeddings_index[word]
            k += vocab[word]
        except:
            oov[word] = vocab[word]
            i += vocab[word]
            pass
        
    print('Found embeddings for {:.2%} of vocab'.format(len(a) / len(vocab)))
    print('Found embeddings for  {:.2%} of all text'.format(k / (k + i)))
    sorted_x = sorted(oov.items(), key = operator.itemgetter(1))[::-1]

    return sorted_x

def build_vocab(sentences, verbose = True):
    vocab = {}
    for sentence in tqdm(sentences, disable = (not verbose)):
        for word in sentence:
            try:
                vocab[word] += 1
            except:
                vocab[word] = 1
    return vocab
    
def get_coefs(word, *arr):
    return word, np.asarray(arr, dtype='float32')


def load_embeddings(path):
    with open(path, encoding = "utf-8") as f:
        return dict(get_coefs(*line.strip().split(' ')) for line in f)


def build_matrix(word_index, path):
    embedding_index = load_embeddings(path)
    embedding_matrix = np.zeros((len(word_index) + 1, 300))
    for word, i in word_index.items():
        try:
            embedding_matrix[i] = embedding_index[word]
        except KeyError:
            pass
    return embedding_matrix

In [28]:
GLOVE_EMBEDDING_FILE = '/content/gdrive/My Drive/glove.840B.300d.txt'
glove_embeddings = load_embeddings(GLOVE_EMBEDDING_FILE)
print(f'loaded {len(glove_embeddings)} word vectors ')

loaded 2196008 word vectors 


In [29]:
print(list(tweet_df))
print(tweet_df)

['coordinates', 'text', 'sentiment_score', 'longitude', 'latitude', 'geometry']
                    coordinates  ...                           geometry
0       77.39760968,28.51873311  ...    POINT (77.39760968 28.51873311)
1      -80.13934722,26.12700768  ...   POINT (-80.13934722 26.12700768)
2            -79.16659,43.77102  ...         POINT (-79.16659 43.77102)
3      -73.87320303,50.42075843  ...   POINT (-73.87320303 50.42075843)
4          110.366643,-7.799243  ...       POINT (110.366643 -7.799243)
...                         ...  ...                                ...
3820   -73.56725453,45.75975883  ...   POINT (-73.56725453 45.75975883)
3821   -123.12316786,49.3158291  ...   POINT (-123.12316786 49.3158291)
3822           -81.9375,34.9535  ...           POINT (-81.9375 34.9535)
3823   -73.56725453,45.75975883  ...   POINT (-73.56725453 45.75975883)
3824  -117.70890816,33.60900796  ...  POINT (-117.70890816 33.60900796)

[3825 rows x 6 columns]


In [31]:
vocab = build_vocab(list(tweet_df['text'].apply(lambda x : x.split())))
oov = check_coverage(vocab, glove_embeddings)
oov[:10]


Found embeddings for 57.39% of vocab
Found embeddings for  90.46% of all text


[('covid', 1894),
 ('covid19', 378),
 ('nroom', 124),
 ('ⓣⓔⓒⓗ', 77),
 ('ⓢⓚⓨ', 77),
 ('biontech', 72),
 ('covidvacccine', 61),
 ('covidvaccine', 54),
 ('the…', 38),
 ('covid19vaccine', 33)]

In [32]:
TWEET = data.Field(sequential = True, lower = True, tokenize = tokenizer)
LABEL = data.Field(sequential = False, use_vocab = False)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
TWEET.build_vocab(train_dataset, vectors = 'glove.840B.300d')

.vector_cache/glove.840B.300d.zip: 2.18GB [08:39, 4.19MB/s]                            
100%|█████████▉| 2195810/2196017 [05:50<00:00, 6587.83it/s]

In [33]:
tweet_field.vocab = TWEET.vocab
BATCH_SIZE = 1
n_label = 11
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

train_iter = data.BucketIterator(train_dataset,
                                batch_size = BATCH_SIZE,
                                sort_key = lambda x : len(x.tweet),
                                sort_within_batch = False,
                                repeat = False,
                                shuffle = False,
                                device = device)

In [34]:

class BatchWrapper():
    def __init__(self, dl, x_var, y_vars):
        self.dl = dl
        self.x_var = x_var
        self.y_vars = y_vars

    def __iter__(self):
        for batch in self.dl:
            x = getattr(batch, self.x_var)
            if self.y_vars is not None:
                y = torch.cat([getattr(batch, feat).unsqueeze(1) for feat in self.y_vars], dim = 1).float()
            else:
                y = torch.zeros((1))
            yield(x, y)
    
    def __len__(self):
        return len(self.dl)

In [35]:
train_dl = BatchWrapper(train_iter, "text", None)

In [36]:
i = 0
for x, y in train_dl:
    print(x.squeeze())
    i += 1
    if i == 10: break

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [37]:
print(train_dl)

In [38]:
predicted_labels = []
sus = []
i = 0
for X, y in train_dl:
    i += 1
    if i not in sus:
        preds = model(X)
        sig = nn.Sigmoid()
        out = sig(preds)

        out[out >= 0.5] = 1
        out[out < 0.5] = 0
        predicted_labels.append(out.detach().cpu().numpy().tolist())
        if i % 100 == 0:
            print("{}/{} iterations done".format(i, len(train_dl)))
    else:
        predicted_labels.append([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])
    if i == 181500:
      break 

100/3825 iterations done
200/3825 iterations done
300/3825 iterations done
400/3825 iterations done
500/3825 iterations done
600/3825 iterations done
700/3825 iterations done
800/3825 iterations done
900/3825 iterations done
1000/3825 iterations done
1100/3825 iterations done
1200/3825 iterations done
1300/3825 iterations done
1400/3825 iterations done
1500/3825 iterations done
1600/3825 iterations done
1700/3825 iterations done
1800/3825 iterations done
1900/3825 iterations done
2000/3825 iterations done
2100/3825 iterations done
2200/3825 iterations done
2300/3825 iterations done
2400/3825 iterations done
2500/3825 iterations done
2600/3825 iterations done
2700/3825 iterations done
2800/3825 iterations done
2900/3825 iterations done
3000/3825 iterations done
3100/3825 iterations done
3200/3825 iterations done
3300/3825 iterations done
3400/3825 iterations done
3500/3825 iterations done
3600/3825 iterations done
3700/3825 iterations done
3800/3825 iterations done


In [39]:
print(len(predicted_labels))
till_now = predicted_labels

3825


In [40]:
classified_df = pd.read_csv('/content/gdrive/My Drive/geo tagged data/geo tagged final.csv', lineterminator='\r')
classified_df = tweet_df.replace('\n','', regex=True)

In [41]:
classified_df['Optimistic'] = "None"
classified_df['Thankful'] = "None"
classified_df['Empathetic'] = "None"
classified_df['Pessimistic'] = "None"
classified_df['Anxious'] = "None"
classified_df['Sad'] = "None"
classified_df['Annoyed'] = "None"
classified_df['Denial'] = "None"
classified_df['Official report'] = "None"
classified_df['Surprise'] = "None"
classified_df['Joking'] = "None"
print(classified_df.head(5))

                coordinates  ... Joking
0   77.39760968,28.51873311  ...   None
1  -80.13934722,26.12700768  ...   None
2        -79.16659,43.77102  ...   None
3  -73.87320303,50.42075843  ...   None
4      110.366643,-7.799243  ...   None

[5 rows x 17 columns]


In [42]:
for i in range(len(till_now)):
    classified_df['Optimistic'].iloc[i] = till_now[i][0]
    classified_df['Thankful'].iloc[i] = till_now[i][1]
    classified_df['Empathetic'].iloc[i] = till_now[i][2]
    classified_df['Pessimistic'].iloc[i] = till_now[i][3]
    classified_df['Anxious'].iloc[i] = till_now[i][4]
    classified_df['Sad'].iloc[i] = till_now[i][5]
    classified_df['Annoyed'].iloc[i] = till_now[i][6]
    classified_df['Denial'].iloc[i] = till_now[i][7]
    classified_df['Official report'].iloc[i] = till_now[i][8]
    classified_df['Surprise'].iloc[i] = till_now[i][9]
    classified_df['Joking'].iloc[i] = till_now[i][10]

In [43]:
classified_df.head()

coordinates  ... Joking
0   77.39760968,28.51873311  ...      1
1  -80.13934722,26.12700768  ...      0
2        -79.16659,43.77102  ...      1
3  -73.87320303,50.42075843  ...      1
4      110.366643,-7.799243  ...      1

[5 rows x 17 columns]

In [44]:
rand_text = classified_df

In [48]:
rand_idx = np.random.randint(0, 101)
print(rand_idx)
print(classified_df.iloc[rand_idx]['text'])
print(classified_df.iloc[rand_idx])

8
how to reduce your risk on the corona virus infection  there is currently no vaccine to prevent coronavirus disease 2019  covid 19   the best way to prevent illness is to avoid being exposed to this virus  the virus… https   t co an4wdqaazi
coordinates                                       -80.14043,26.10736
text               how to reduce your risk on the corona virus in...
sentiment_score                                                  0.5
longitude                                                   -80.1404
latitude                                                     26.1074
geometry                         POINT (-80.14042999999999 26.10736)
Optimistic                                                         0
Thankful                                                           0
Empathetic                                                         0
Pessimistic                                                        0
Anxious                                                            

In [ ]:
categories = list(classified_df.columns[2:].values)
sns.set(font_scale = 2)

plt.figure(figsize = (15, 8))
ax= sns.barplot(classified_df.iloc[:, 2:].sum().values, categories, orient = 'h')
plt.title("Distribution of Emotions", fontsize = 24)
plt.xlabel('Number of Tweets', fontsize = 18)
plt.ylabel('Emotion type', fontsize = 18)

#adding the text labels
rects = ax.patches
labels = classified_df.iloc[:, 2:].sum().values
for rect, label in zip(rects, labels):
    height = rect.get_height()
    #ax.text(rect.get_x() + rect.get_width()/2, height + 5, label, ha = 'center', va = 'bottom', fontsize = 18)
plt.show()

KeyError: ignored

<Figure size 1080x576 with 0 Axes>

In [ ]:
from wordcloud import WordCloud, STOPWORDS